### ISSUE TITLE
builds failing

### ISSUE THREAD

**Issue by ddkohler** [yaq-project/yaqd-ni#48]
Excerpt
```
Building wheels for collected packages: pendulum, snaptime
        Building wheel for pendulum (pyproject.toml): started
        Building wheel for pendulum (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for pendulum (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [27 lines of output]
            Traceback (most recent call last):
              File "/tmp/pip-install-l_io5eeg/pendulum_8abc2634445a4b12972452fa4a5f6771/build.py", line 5, in <module>
                from distutils.command.build_ext import build_ext
            ModuleNotFoundError: No module named 'distutils'
            Traceback (most recent call last):
              File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/tmp/pip-build-env-ckadeh8s/overlay/lib/python3.12/site-packages/poetry/core/masonry/api.py", line 58, in build_wheel
                return WheelBuilder.make_in(
                       ^^^^^^^^^^^^^^^^^^^^^
              File "/tmp/pip-build-env-ckadeh8s/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 88, in make_in
                wb.build(target_dir=directory)
              File "/tmp/pip-build-env-ckadeh8s/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 123, in build
                self._build(zip_file)
              File "/tmp/pip-build-env-ckadeh8s/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 172, in _build
                self._run_build_script(self._package.build_script)
              File "/tmp/pip-build-env-ckadeh8s/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 266, in _run_build_script
                subprocess.check_call([self.executable.as_posix(), build_script])
              File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/subprocess.py", line 413, in check_call
                raise CalledProcessError(retcode, cmd)
            subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.12.0/x64/bin/python', 'build.py']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pendulum
        Building wheel for snaptime (pyproject.toml): started
        Building wheel for snaptime (pyproject.toml): finished with status 'done'
        Created wheel for snaptime: filename=snaptime-0.2.4-py3-none-any.whl size=3569 sha256=273f1bee2bf9613910b33b0b6071a48a0ce[195](https://github.com/yaq-project/yaqd-attune/actions/runs/7146886317/job/19465441189?pr=40#step:4:196)aef381a140ab4ad3ebf3e535aa
        Stored in directory: /home/runner/.cache/pip/wheels/2a/ba/b2/d779a860fe137d40789da122a1f61d24c706ec317e137ff049
      Successfully built snaptime
      Failed to build pendulum
      ERROR: Could not build wheels for pendulum, which is required to install pyproject.toml-based projects
```

We are not the only ones dealing with pendulum maintenance issues.

**Comment by ddkohler** [comment]
sorry wrong package
